#!/bin/sh

IP_SUBNET="1"
IP_NET="200"

case $1 in
        start)
                killall udhcpc
                ifconfig eth0 192.168.$IP_SUBNET.$IP_NET netmask 255.255.255.0
                route add default gw 192.168.$IP_SUBNET.1
                echo "nameserver 8.8.8.8" > /etc/resolv.conf

                ;;
        stop)
                ;;
        *)
                exit 1
                ;;
esac

